export const queryKeys = {
  dashboard: {
    summary: ["dashboard", "summary"],
    systemStatus: ["dashboard", "system-status"],
    ciaRisk: ["dashboard", "cia-risk"],
    recentIncidents: ["dashboard", "recent-incidents"],
    recentAlerts: ["dashboard", "recent-alerts"],
  },
  integrations: {
    status: (refresh = false) => ["integrations", "status", { refresh }],
    schema: ["integrations", "schema"],
    systemInfo: ["integrations", "system-info"],
  },
  incidents: {
    list: (filters = {}) => ["incidents", "list", filters],
    detail: (id) => ["incidents", "detail", id],
    evidence: (id) => ["incidents", "evidence", id],
    timeline: (id) => ["incidents", "timeline", id],
    containment: (id) => ["incidents", "containment", id],
    triggeredAlert: (id) => ["incidents", "triggered-alert", id],
    workflow: (id) => ["incidents", "workflow", id],
    comments: (id) => ["incidents", "comments", id],
    activity: (id) => ["incidents", "activity", id],
  },
  assets: {
    list: (filters = {}) => ["assets", "list", filters],
    detail: (id) => ["assets", "detail", id],
  },
  splunk: {
    alerts: ["splunk", "alerts"],
    reports: ["splunk", "reports"],
    savedSearches: ["splunk", "saved-searches"],
    triggeredAlerts: ["splunk", "triggered-alerts"],
    search: (params = {}) => ["splunk", "search", params],
    logChain: (params = {}) => ["splunk", "log-chain", params],
  },
  reports: {
    list: ["reports", "list"],
    detail: (id) => ["reports", "detail", id],
    results: (params = {}) => ["reports", "results", params],
  },
  response: {
    firewallStatus: ["response", "firewall-status"],
    firewallActions: ["response", "firewall-actions"],
    containmentHistory: ["response", "containment-history"],
    blockedIps: ["response", "blocked-ips"],
  },
  mitre: {
    matrix: ["mitre", "matrix"],
    health: ["mitre", "health"],
    incident: (id) => ["mitre", "incident", id],
  },
  reputation: {
    ip: (ip) => ["reputation", "ip", ip],
    incident: (id) => ["reputation", "incident", id],
    observations: (ip) => ["reputation", "observations", ip],
    recent: ["reputation", "recent"],
    queueStatus: ["reputation", "queue-status"],
    providerStatus: ["reputation", "provider-status"],
  },
  account: {
    currentUser: ["account", "current-user"],
    profile: ["account", "profile"],
    preferences: ["account", "preferences"],
    mfaStatus: ["account", "mfa-status"],
    loginHistory: ["account", "login-history"],
    trustedDevices: ["account", "trusted-devices"],
  },
};
